# Generated by Django 6.0.4 on 2026-05-16 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_app', '0002_alter_project_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateTimeField()),
                ('participant_count', models.IntegerField(blank=True)),
                ('next_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_event', to='event_app.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.IntegerField(blank=True)),
                ('count_per_case', models.IntegerField(blank=True)),
                ('count', models.IntegerField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.event')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='event',
            field=models.ManyToManyField(related_name='inventory_history', through='event_app.InventoryPerEvent', to='event_app.event'),
        ),
    ]
