# Generated by Django 6.0.4 on 2026-05-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryperevent',
            old_name='cases',
            new_name='case_count',
        ),
        migrations.RenameField(
            model_name='inventoryperevent',
            old_name='count',
            new_name='item_count',
        ),
    ]
