# Generated by Django 6.0.4 on 2026-05-16 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='next_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_event', to='event_app.event'),
        ),
    ]
