# Generated by Django 6.0.4 on 2026-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_alter_event_next_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryperevent',
            name='count_per_case',
        ),
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inventory',
            name='count_per_case',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
