# Generated by Django 6.0.4 on 2026-05-16 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_remove_inventoryperevent_count_per_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryperevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryperevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
