# Generated by Django 6.0.4 on 2026-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_inventoryperevent_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
