# Generated by Django 6.0.4 on 2026-05-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='event',
            new_name='events',
        ),
    ]
