# Generated by Django 6.0.4 on 2026-05-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_rename_event_inventory_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryPerEvent',
            new_name='EventInventoryRelation',
        ),
    ]
