# Generated by Django 6.0.4 on 2026-05-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_rename_inventoryperevent_eventinventoryrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='next_event',
        ),
        migrations.AddField(
            model_name='event',
            name='previous_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_event', to='event_app.event'),
        ),
    ]
