# Generated by Django 6.0.4 on 2026-05-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0010_remove_event_next_event_event_previous_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='inventory',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', through='event_app.EventInventoryRelation', to='event_app.inventory'),
        ),
    ]
