# Generated by Django 6.0.4 on 2026-05-17 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_remove_inventory_events_event_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='previous_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_event', to='event_app.event'),
        ),
    ]
