# Generated by Django 6.0.4 on 2026-05-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0014_alter_event_previous_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventinventoryrelation',
            unique_together={('event', 'inventory')},
        ),
    ]
