# Generated by Django 6.0.4 on 2026-05-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0015_alter_eventinventoryrelation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('count_per_case', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='count_per_case',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='project',
        ),
        migrations.AddField(
            model_name='inventory',
            name='event',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='event_app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='names',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='InventoryItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_count', models.IntegerField(blank=True)),
                ('item_count', models.IntegerField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.item')),
            ],
            options={
                'unique_together': {('item', 'inventory')},
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='inventory', through='event_app.InventoryItemRelation', to='event_app.item'),
        ),
        migrations.DeleteModel(
            name='EventInventoryRelation',
        ),
    ]
