# Generated by Django 6.0.4 on 2026-05-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0016_item_remove_event_inventory_remove_inventory_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='names',
            new_name='name',
        ),
    ]
