# Generated by Django 6.0.4 on 2026-05-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0017_rename_names_inventory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='previous_inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_inventory', to='event_app.inventory'),
        ),
    ]
