# Generated by Django 6.0.4 on 2026-05-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0018_inventory_previous_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_app.event'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='inventory', through='event_app.InventoryItemRelation', to='event_app.item'),
        ),
        migrations.AlterField(
            model_name='inventoryitemrelation',
            name='case_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitemrelation',
            name='item_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
