# Generated by Django 6.0.4 on 2026-05-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_add_rule_and_relation_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='history',
        ),
    ]
