# Generated by Django 6.0.4 on 2026-05-30 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0019_alter_event_participant_count_alter_inventory_event_and_more'),
        ('task_app', '0004_remove_rule_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='event_app.event'),
        ),
    ]
