# Generated by Django 6.0.4 on 2026-05-31 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_task_event_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='task_app.project'),
        ),
    ]
