# Generated by Django 6.0.4 on 2026-06-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_userpreferences_default_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
