# Generated by Django 6.0.4 on 2026-06-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0016_clear_dev_branch_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='task_app.tasktype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='task_app.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
