# Generated by Django 6.0.4 on 2026-06-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0018_add_task_type_fk_to_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('field_type', models.CharField(choices=[('text', 'テキスト'), ('url', 'URL'), ('number', '数値'), ('textarea', 'テキストエリア')], default='text', max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='task_app.tasktype')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('task_type', 'name')},
            },
        ),
    ]
