# Generated by Django 6.0.4 on 2026-06-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0019_add_tasktypefield_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='task_app.tasktypefield')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='task_app.task')),
            ],
            options={
                'unique_together': {('task', 'field')},
            },
        ),
    ]
