# Generated by Django 6.0.4 on 2026-06-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0020_add_taskfieldvalue_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
