# Generated by Django 6.0.4 on 2026-06-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0021_add_project_agent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
