# Generated by Django 6.0.4 on 2026-06-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0022_tasktype_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='agent',
        ),
    ]
