# Generated by Django 6.0.4 on 2026-07-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0023_remove_project_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTypeStatusAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.TextField(blank=True, default='')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_type_agents', to='task_app.status')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_agents', to='task_app.tasktype')),
            ],
            options={
                'ordering': ['task_type', 'status'],
                'unique_together': {('task_type', 'status')},
            },
        ),
    ]
